### ISSUE TITLE
How to bypass Vanguard?

### ISSUE THREAD

**Issue by BaiFeng666** [cMiraka/Guarded-Regions-Bypass-Valorant#30]
when i load driver, vanguard will intercept

**Comment by deprale** [comment]
decrypt the vanguard logs and try to code **around** the logs!!

**Comment by Exotikcheatt** [comment]
any hook win32 = ban anyway

**Comment by deprale** [comment]
no bro, win32 hook ud just code around the driver!! and logs!! and don't forget to clear precache folders!!!

**Comment by Exotikcheatt** [comment]
> no bro, win32 hook ud just code around the driver!! and logs!! and don't forget to clear precache folders!!!

I have always been told the opposite Win32, anyway I use no driver hook I use ioctl  + Mapping driver with KDP + 2 line code and no ban after 1 month on apex legends I haven't tested on Valorant because I don't play and I have trouble simply updating a Fortnite external so imagine on Valorant xD but no problem with apex legends
